export const images = {
  logoDark: "logo-dark-trans.png",
  icons: {
    settings: "icons/settings.png",
    info: "icons/info.png",
    nickname: "icons/nickname.png",
    connect: "icons/connect.png",
    locked: "icons/locked.png",
    unlocked: "icons/unlocked.png",
    omp: "icons/omp.png",
    ompLight: "icons/omp-light.png",
    search: "icons/search.png",
    filter: "icons/filter.png",
    favorite: "icons/favorite.png",
    unfavorite: "icons/unfavorite.png",
    partner: "icons/partner.png",
    internet: "icons/internet.png",
    recently: "icons/recently.png",
    copy: "icons/copy.png",
    windowClose: "icons/window_close.svg",
    windowMinimize: "icons/window_minimize.svg",
    windowMaximize: "icons/window_maximize.svg",
    openSideLists: "icons/open_side_lists.svg",
    closeSideLists: "icons/close_side_lists.svg",
    favAdd: "icons/fav_add.svg",
    favRemove: "icons/fav_remove.svg",
    play: "icons/play.svg",
    add: "icons/add.png",
    language: "icons/language.svg",
    users: "icons/users.svg",
    game: "icons/game.svg",
    close: "icons/close.svg",
  },
};
