import { Server } from "./types";

export const mockServers: Server[] = [
  {
    ip: "127.0.0.1",
    port: 7777,
    hostname: "Just a FreeRoam server as a test, using OMP",
    playerCount: 3,
    maxPlayers: 50,
    gameMode: "TDM | DM | FR",
    language: "FA/EN",
    hasPassword: true,
    version: "0.3.7-R2",
    usingOmp: true,
    ping: 152,
    players: [
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
    ],
    rules: {
      artwork: "Yes",
      mapname: "San Andreas",
      lagcomp: "On",
      version: "0.3.7-R2",
      weather: "sunny",
      weburl: "https://amii.ir/",
      worldtime: "12:00",
    },
  },
  {
    ip: "127.0.0.1",
    port: 7778,
    hostname: "Just a FreeRoam server as a test, using SAMP",
    playerCount: 1000,
    maxPlayers: 1000,
    gameMode: "TDM | DM | FR",
    language: "FA/EN",
    hasPassword: false,
    version: "0.3.7-R2",
    usingOmp: false,
    ping: 24622,
    players: [
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
    ],
    rules: {
      artwork: "Yes",
      mapname: "San Andreas",
      lagcomp: "On",
      version: "0.3.7-R2",
      weather: "sunny",
      weburl: "https://amii.ir/",
      worldtime: "12:00",
    },
  },
  {
    ip: "127.0.0.1",
    port: 7779,
    hostname: "Just a FreeRoam server as a test, using SAMP",
    playerCount: 1000,
    maxPlayers: 1000,
    gameMode: "TDM | DM | FR",
    language: "FA/EN",
    hasPassword: false,
    version: "0.3.7-R2",
    usingOmp: false,
    ping: 24622,
    players: [
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
    ],
    rules: {
      artwork: "Yes",
      mapname: "San Andreas",
      lagcomp: "On",
      version: "0.3.7-R2",
      weather: "sunny",
      weburl: "https://amii.ir/",
      worldtime: "12:00",
    },
  },
  {
    ip: "127.0.0.1",
    port: 7780,
    hostname: "Just a FreeRoam server as a test, using SAMP",
    playerCount: 1000,
    maxPlayers: 1000,
    gameMode: "TDM | DM | FR",
    language: "FA/EN",
    hasPassword: false,
    version: "0.3.7-R2",
    usingOmp: false,
    ping: 24622,
    players: [
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
    ],
    rules: {
      artwork: "Yes",
      mapname: "San Andreas",
      lagcomp: "On",
      version: "0.3.7-R2",
      weather: "sunny",
      weburl: "https://amii.ir/",
      worldtime: "12:00",
    },
  },
  {
    ip: "127.0.0.1",
    port: 7781,
    hostname: "Just a FreeRoam server as a test, using SAMP",
    playerCount: 1000,
    maxPlayers: 1000,
    gameMode: "TDM | DM | FR",
    language: "FA/EN",
    hasPassword: false,
    version: "0.3.7-R2",
    usingOmp: false,
    ping: 24622,
    players: [
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
    ],
    rules: {
      artwork: "Yes",
      mapname: "San Andreas",
      lagcomp: "On",
      version: "0.3.7-R2",
      weather: "sunny",
      weburl: "https://amii.ir/",
      worldtime: "12:00",
    },
  },
  {
    ip: "127.0.0.1",
    port: 7782,
    hostname: "Just a FreeRoam server as a test, using SAMP",
    playerCount: 1000,
    maxPlayers: 1000,
    gameMode: "TDM | DM | FR",
    language: "FA/EN",
    hasPassword: false,
    version: "0.3.7-R2",
    usingOmp: false,
    ping: 24622,
    players: [
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
    ],
    rules: {
      artwork: "Yes",
      mapname: "San Andreas",
      lagcomp: "On",
      version: "0.3.7-R2",
      weather: "sunny",
      weburl: "https://amii.ir/",
      worldtime: "12:00",
    },
  },
  {
    ip: "127.0.0.1",
    port: 7783,
    hostname: "Just a FreeRoam server as a test, using SAMP",
    playerCount: 1000,
    maxPlayers: 1000,
    gameMode: "TDM | DM | FR",
    language: "FA/EN",
    hasPassword: false,
    version: "0.3.7-R2",
    usingOmp: false,
    ping: 24622,
    players: [
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
    ],
    rules: {
      artwork: "Yes",
      mapname: "San Andreas",
      lagcomp: "On",
      version: "0.3.7-R2",
      weather: "sunny",
      weburl: "https://amii.ir/",
      worldtime: "12:00",
    },
  },
  {
    ip: "127.0.0.1",
    port: 7784,
    hostname: "Just a FreeRoam server as a test, using SAMP",
    playerCount: 1000,
    maxPlayers: 1000,
    gameMode: "TDM | DM | FR",
    language: "FA/EN",
    hasPassword: false,
    version: "0.3.7-R2",
    usingOmp: false,
    ping: 24622,
    players: [
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
    ],
    rules: {
      artwork: "Yes",
      mapname: "San Andreas",
      lagcomp: "On",
      version: "0.3.7-R2",
      weather: "sunny",
      weburl: "https://amii.ir/",
      worldtime: "12:00",
    },
  },
  {
    ip: "127.0.0.1",
    port: 7785,
    hostname: "Just a FreeRoam server as a test, using SAMP",
    playerCount: 1000,
    maxPlayers: 1000,
    gameMode: "TDM | DM | FR",
    language: "FA/EN",
    hasPassword: false,
    version: "0.3.7-R2",
    usingOmp: false,
    ping: 24622,
    players: [
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
    ],
    rules: {
      artwork: "Yes",
      mapname: "San Andreas",
      lagcomp: "On",
      version: "0.3.7-R2",
      weather: "sunny",
      weburl: "https://amii.ir/",
      worldtime: "12:00",
    },
  },
  {
    ip: "127.0.0.1",
    port: 7786,
    hostname: "Just a FreeRoam server as a test, using SAMP",
    playerCount: 1000,
    maxPlayers: 1000,
    gameMode: "TDM | DM | FR",
    language: "FA/EN",
    hasPassword: false,
    version: "0.3.7-R2",
    usingOmp: false,
    ping: 24622,
    players: [
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
    ],
    rules: {
      artwork: "Yes",
      mapname: "San Andreas",
      lagcomp: "On",
      version: "0.3.7-R2",
      weather: "sunny",
      weburl: "https://amii.ir/",
      worldtime: "12:00",
    },
  },
  {
    ip: "127.0.0.1",
    port: 7787,
    hostname: "Just a FreeRoam server as a test, using SAMP",
    playerCount: 1000,
    maxPlayers: 1000,
    gameMode: "TDM | DM | FR",
    language: "FA/EN",
    hasPassword: false,
    version: "0.3.7-R2",
    usingOmp: false,
    ping: 24622,
    players: [
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
    ],
    rules: {
      artwork: "Yes",
      mapname: "San Andreas",
      lagcomp: "On",
      version: "0.3.7-R2",
      weather: "sunny",
      weburl: "https://amii.ir/",
      worldtime: "12:00",
    },
  },
  {
    ip: "127.0.0.1",
    port: 7788,
    hostname: "Just a FreeRoam server as a test, using SAMP",
    playerCount: 1000,
    maxPlayers: 1000,
    gameMode: "TDM | DM | FR",
    language: "FA/EN",
    hasPassword: false,
    version: "0.3.7-R2",
    usingOmp: false,
    ping: 24622,
    players: [
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
      { name: "amir", score: 15 },
    ],
    rules: {
      artwork: "Yes",
      mapname: "San Andreas",
      lagcomp: "On",
      version: "0.3.7-R2",
      weather: "sunny",
      weburl: "https://amii.ir/",
      worldtime: "12:00",
    },
  },
  {
    ip: "127.0.0.1",
    port: 7790,
    hostname: "Just a FreeRoam server as a test, using OMP",
    playerCount: 74,
    maxPlayers: 500,
    gameMode: "TDM | DM | FR",
    language: "FA/EN",
    hasPassword: false,
    version: "0.3.7-R2",
    usingOmp: true,
    ping: 152,
    players: [
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
    ],
    rules: {
      artwork: "Yes",
      mapname: "San Andreas",
      lagcomp: "On",
      version: "0.3.7-R2",
      weather: "sunny",
      weburl: "https://amii.ir/",
      worldtime: "12:00",
    },
  },
  {
    ip: "127.0.0.1",
    port: 7791,
    hostname: "Just a FreeRoam server as a test, using OMP",
    playerCount: 74,
    maxPlayers: 500,
    gameMode: "TDM | DM | FR",
    language: "FA/EN",
    hasPassword: false,
    version: "0.3.7-R2",
    usingOmp: true,
    ping: 152,
    players: [
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
    ],
    rules: {
      artwork: "Yes",
      mapname: "San Andreas",
      lagcomp: "On",
      version: "0.3.7-R2",
      weather: "sunny",
      weburl: "https://amii.ir/",
      worldtime: "12:00",
    },
  },
  {
    ip: "127.0.0.1",
    port: 7792,
    hostname: "Just a FreeRoam server as a test, using OMP",
    playerCount: 74,
    maxPlayers: 500,
    gameMode: "TDM | DM | FR",
    language: "FA/EN",
    hasPassword: false,
    version: "0.3.7-R2",
    usingOmp: true,
    ping: 152,
    players: [
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
    ],
    rules: {
      artwork: "Yes",
      mapname: "San Andreas",
      lagcomp: "On",
      version: "0.3.7-R2",
      weather: "sunny",
      weburl: "https://amii.ir/",
      worldtime: "12:00",
    },
  },
  {
    ip: "127.0.0.1",
    port: 7793,
    hostname: "Just a FreeRoam server as a test, using OMP",
    playerCount: 74,
    maxPlayers: 500,
    gameMode: "TDM | DM | FR",
    language: "FA/EN",
    hasPassword: false,
    version: "0.3.7-R2",
    usingOmp: true,
    ping: 152,
    players: [
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
    ],
    rules: {
      artwork: "Yes",
      mapname: "San Andreas",
      lagcomp: "On",
      version: "0.3.7-R2",
      weather: "sunny",
      weburl: "https://amii.ir/",
      worldtime: "12:00",
    },
  },
  {
    ip: "127.0.0.1",
    port: 7794,
    hostname: "Just a FreeRoam server as a test, using OMP",
    playerCount: 74,
    maxPlayers: 500,
    gameMode: "TDM | DM | FR",
    language: "FA/EN",
    hasPassword: false,
    version: "0.3.7-R2",
    usingOmp: true,
    ping: 152,
    players: [
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
    ],
    rules: {
      artwork: "Yes",
      mapname: "San Andreas",
      lagcomp: "On",
      version: "0.3.7-R2",
      weather: "sunny",
      weburl: "https://amii.ir/",
      worldtime: "12:00",
    },
  },
  {
    ip: "127.0.0.1",
    port: 7795,
    hostname: "Just a FreeRoam server as a test, using OMP",
    playerCount: 74,
    maxPlayers: 500,
    gameMode: "TDM | DM | FR",
    language: "FA/EN",
    hasPassword: false,
    version: "0.3.7-R2",
    usingOmp: true,
    ping: 152,
    players: [
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
    ],
    rules: {
      artwork: "Yes",
      mapname: "San Andreas",
      lagcomp: "On",
      version: "0.3.7-R2",
      weather: "sunny",
      weburl: "https://amii.ir/",
      worldtime: "12:00",
    },
  },
  {
    ip: "127.0.0.1",
    port: 7796,
    hostname: "Just a FreeRoam server as a test, using OMP",
    playerCount: 74,
    maxPlayers: 500,
    gameMode: "TDM | DM | FR",
    language: "FA/EN",
    hasPassword: false,
    version: "0.3.7-R2",
    usingOmp: true,
    ping: 152,
    players: [
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
    ],
    rules: {
      artwork: "Yes",
      mapname: "San Andreas",
      lagcomp: "On",
      version: "0.3.7-R2",
      weather: "sunny",
      weburl: "https://amii.ir/",
      worldtime: "12:00",
    },
  },
  {
    ip: "127.0.0.1",
    port: 7797,
    hostname: "Just a FreeRoam server as a test, using OMP",
    playerCount: 74,
    maxPlayers: 500,
    gameMode: "TDM | DM | FR",
    language: "FA/EN",
    hasPassword: false,
    version: "0.3.7-R2",
    usingOmp: true,
    ping: 152,
    players: [
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
    ],
    rules: {
      artwork: "Yes",
      mapname: "San Andreas",
      lagcomp: "On",
      version: "0.3.7-R2",
      weather: "sunny",
      weburl: "https://amii.ir/",
      worldtime: "12:00",
    },
  },
  {
    ip: "127.0.0.1",
    port: 7798,
    hostname: "Just a FreeRoam server as a test, using OMP",
    playerCount: 74,
    maxPlayers: 500,
    gameMode: "TDM | DM | FR",
    language: "FA/EN",
    hasPassword: false,
    version: "0.3.7-R2",
    usingOmp: true,
    ping: 152,
    players: [
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
    ],
    rules: {
      artwork: "Yes",
      mapname: "San Andreas",
      lagcomp: "On",
      version: "0.3.7-R2",
      weather: "sunny",
      weburl: "https://amii.ir/",
      worldtime: "12:00",
    },
  },
  {
    ip: "127.0.0.1",
    port: 7799,
    hostname: "Just a FreeRoam server as a test, using OMP",
    playerCount: 74,
    maxPlayers: 500,
    gameMode: "TDM | DM | FR",
    language: "FA/EN",
    hasPassword: false,
    version: "0.3.7-R2",
    usingOmp: true,
    ping: 152,
    players: [
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
    ],
    rules: {
      artwork: "Yes",
      mapname: "San Andreas",
      lagcomp: "On",
      version: "0.3.7-R2",
      weather: "sunny",
      weburl: "https://amii.ir/",
      worldtime: "12:00",
    },
  },
  {
    ip: "127.0.0.1",
    port: 7801,
    hostname: "Just a FreeRoam server as a test, using OMP",
    playerCount: 74,
    maxPlayers: 500,
    gameMode: "TDM | DM | FR",
    language: "FA/EN",
    hasPassword: false,
    version: "0.3.7-R2",
    usingOmp: true,
    ping: 152,
    players: [
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
      { name: "ali", score: 15 },
      { name: "amir", score: 15 },
      { name: "mamad", score: 15 },
      { name: "teddy", score: 15 },
    ],
    rules: {
      artwork: "Yes",
      mapname: "San Andreas",
      lagcomp: "On",
      version: "0.3.7-R2",
      weather: "sunny",
      weburl: "https://amii.ir/",
      worldtime: "12:00",
    },
  },
];
